package com.accenture.adf.newcodington.module8.sample;

/*
 * Travel Pass Lottery Demo is about choosing lucky winner among the ticket ID's generated
 * 
 * Topic: Demo on linear search using single dimensional array
 * 
 */

//TODO 1. Create a public class named 'TravelPassLottery_Demo1' 

//TODO 2. Create a public, static method called main() that has one parameter 
//          that is a String array called 'args' and doesn't return any values

//TODO 3. Declare an integer for no of tickets issued

//TODO 4. Declare an single dimensional integer array for ticket id's

//TODO 5. Declare an integer variable for generated ticket id

//TODO 6. Declare a boolean variable for winner found flag

//TODO 7. Initialize the variables no of tickets, ticket id array with no of tickets as the size

//TODO 8. Print a message to the console as 'Travel Pass Lottery - Choosing Winner'

//TODO 9. Use for loop with noOfTickets as the boundary to populate the ticket ID array
// 			a. Ticket ID can be generated by adding 1 to the loop index
// 			b. Assign ticket id generated to the respective index in the array

//TODO 10. Assign some random integer as the lucky winner id, store this value in ticket id

//TODO 11. Use for loop to check the array values with array length as the boundary
// 			a. Check each array value if it matches with the lucky winner id
// 			b. If matches, set winner found to true and break the loop

//TODO 12. If winner found is true, print a message to the console as Hurrah, winner among us

//TODO 13. If winner found false, print a message to the console as Oops, winner not among us

//TODO 14. Save the file