package com.accenture.adf.newcodington.module7.sample;

/**
 * 
 * Travel Pass Demo on checking the number of tickets assigned ticket ID's
 * 
 * Topic: Demo on error handling using assert
 * 
 */
public class TravelPass_Demo1 {

	public static void main(String[] args) {
		int numTickets;
		int[] ticketIDs;
		numTickets = 5;
		ticketIDs = new int[numTickets];

		System.out.println("Checking Ticket ID's");

		int passId = 0;
		for (int i = 0; i < ticketIDs.length; i++) {

			ticketIDs[i] = passId+1;
			passId++;
			System.out.print(ticketIDs[i] + " ");
		}// end for loop

		int i = 0;
		while (i < ticketIDs.length) {
			assert (ticketIDs[i] != 0) : "Mismatch in issuance of ticket id's'.";
			i++;
		}

		System.out
				.println("Ticket ID's are assigned to total number of tickets issued.");
	}
}
// TODO 1. Create a public class named 'TravelPass_Demo1' with main method()

// TODO 2. Create a public, static method called main() that has one parameter
// that is a String array called 'args' and doesn't return any values

// TODO 3. Declare an integer for no of tickets issued inside main() method

// TODO 4. Declare an integer single dimensional array for ticket id's

// TODO 5. Initialize the variables no of tickets and the ticket id array (with
// no of tickets as the size)

// TODO 6. Print a message to the console as 'Checking Ticket ID's'

// TODO 7. Use for loop with no of tickets as the boundary to generate ticket id
// and populate the ticket id array
// a. Ticket id's can be generated by adding 1 to the loop index
// b. Assign ticket id generated to the respective index in the array

// TODO 8. Declare an integer variable for the loop index and initialize with
// zero (in main() method)

// TODO 9. Loop through the array using a while loop with array size as the
// boundary

// TODO 10. Verify each value of the ticket id array is not equal to zero using
// assert statement

// TODO 11. If equal to zero, print a message to the console as 'Mismatch in
// issuance of ticket id's' as an assertion error

// TODO 12. Otherwise, increase the loop index and verify all the values in the
// array

// TODO 13. In case no assertion errors, print
// "Ticket ID's are assigned to total number of tickets issued." to the console
// after exiting the loop

// TODO 14. Save the file