package com.accenture.adf.newcodington.module20.activity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 * Class that demonstrates usage of JOIN for retrieving data from ZOO and EVENT tables in mySQL database
 */
public class ZooEventsDao {

	// Connection from JDBC API for establishing connection to underlying
	// database
	Connection connection = null;
	// PreparedStatement is used to execute pre-compiled SQL queries for JDBC
	// insertions
	PreparedStatement statement = null;
	// Resultset object to store data retrieved from query. 
	ResultSet resultSet=null;
	// Constant string that captures QUERY to be executed by JDBC statements
	static String DISPLAYQUERY = "select z.zooname, z.animalcount, e.eventname, e.description, e.duration, e.schedule, e.ticketprice " +
			" from zoo z, event e, place p where z.placeid=e.placeid and e.placeid=p.placeid and z.zooname=?";

	
	/**
	 * Method to capture event details for a particular ZOO and information will be <br/>
	 * retrieved by providing ZOONAME and returns data in String format.  <br/>
	 * use statement from JDBC to execute query to capture data <br/>
	 * into resultset and load values from resultset appended to the String "eventData".
	 * @param zooname
	 * @return
	 * @throws SQLException
	 * @throws ClassNotFoundException
	 */
	public String displayEventsOfZoo(String zooname) throws SQLException,ClassNotFoundException
	{
		connection=ConnectionToDB.getConnection();
		String eventData="";
		
		// TODO insert code here
		// ----------------------------------------------------------------------------
		// use statement from JDBC to execute query to capture data
		// into resultset and load values from resultset appended to the String "eventData" 
		// ----------------------------------------------------------------------------
		ConnectionToDB.closeConnection();
		return eventData;
	}
	/**
	 * MAIN method for executing the JOIN
	 * @param args
	 */
	public static void main(String[] args) {
		
		ZooEventsDao dao=new ZooEventsDao();
		String eventsName=""; // String to hold return value from DAO method
		try
		{
		eventsName=dao.displayEventsOfZoo("SouthTown Zoo"); // passing ZOONAME to the method to capture EVENTS mapped to that ZOO 
		}
		catch (SQLException e) // handles the EXCEPTION for SQL queries
		{
			// TODO insert code here
			// --------------------------------------------------------------------------
			// Display the exception message generated by SQL
			// --------------------------------------------------------------------------
		} catch (ClassNotFoundException e) // handles exceptions for mySQL
											// DRIVER
		{
			// TODO insert code here
			// --------------------------------------------------------------------------
			// Display the exception message generated by Class
			// --------------------------------------------------------------------------
		}
		System.out.println("Events is :\n"+eventsName);
		
	}
	
}
